check_dir_exist – uEMEP
check_dir_exist Function
17 statements
Source File
public function check_dir_exist(path) result(exists)
Checks if a directory exists and/or if we have write permission in that directory.
Returns .true. if directory exists and is accessible
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: path
Directory path
Return Value logical
Called by
Source Code
    function check_dir_exist(path) result(exists)
        !! Checks if a directory exists and/or if we have write permission
        !! in that directory.
        !!
        !! Returns .true. if directory exists and is accessible
        character(len=*), intent(in) :: path !! Directory path
        logical:: exists
        ! Local variables
        integer :: u, ios, len_trimmed
        ! Get length of directory path
        len_trimmed = len_trim(path)
        ! Attempt to open a temporary file in the specified directory
        if (path(len_trimmed:len_trimmed) == "/") then
            open(newunit=u, file=trim(path)//"tmp", status="new", iostat=ios)
        else
            open(newunit=u, file=trim(path)//"/tmp", status="new", iostat=ios)
        end if
        if (ios /= 0) then
            exists = .false.
        else
            ! If succesfull, delete the temporary file
            close(unit=u, status="delete")
            exists = .true.
        end if
    end function check_dir_exist
Call graph
uemep_read_config calls check_dir_exist
uemep_save_emission_netcdf calls check_dir_exist
uemep_calculate_emissions_for_emep calls uemep_save_emission_netcdf
uemep_v6 calls uemep_read_config, uemep_calculate_emissions_for_emep