check – uEMEP
check Subroutine
9 statements
Source File
public subroutine check(status)
Uses
netcdf
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: status
Calls
Called by
Source Code
    subroutine check(status)
        use netcdf
        implicit none
        integer, intent ( in) :: status
        if(status /= nf90_noerr) then
            write(*,*) 'Stopping due to netcdf error: '//trim(nf90_strerror(status))
            error stop
        end if
    end subroutine check
Call graph
check calls nf90_strerror
uemep_save_for_emep_netcdf_file calls check
uemep_save_netcdf_file calls check
uemep_save_netcdf_receptor_file calls check
uemep_save_emission_netcdf calls uemep_save_for_emep_netcdf_file
uemep_save_netcdf_control calls uemep_save_netcdf_file, uemep_save_netcdf_receptor_file
uemep_calculate_emissions_for_emep calls uemep_save_emission_netcdf
uemep_v6 calls uemep_save_netcdf_control, uemep_calculate_emissions_for_emep