datestr_to_date – uEMEP
datestr_to_date Subroutine
42 statements
Source File
public subroutine datestr_to_date(date_str, format_str, date_array)
Converts date string to a date array based on the format string
Example: call datestr_to_date("20190429123005", "yyyymmdd", date_array_out) Returns: date_arrat_out = [2019, 4, 29, 0, 0, 0]
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: date_str
Date string [yyyymmddHHMMSS]
character(len=*), intent(in) :: format_str
Format string
integer, intent(out) :: date_array(6)
Datetime [y,m,d,h,m,s]
Called by
Source Code
    subroutine datestr_to_date(date_str, format_str, date_array)
        !! Converts date string to a date array based on the format string
        !!
        !! Example:
        !!     call datestr_to_date("20190429123005", "yyyymmdd", date_array_out)
        !! Returns:
        !!     date_arrat_out = [2019, 4, 29, 0, 0, 0]
        character(*), intent(in) :: date_str !! Date string [yyyymmddHHMMSS]
        character(*), intent(in) :: format_str !! Format string
        integer, intent(out) :: date_array(6) !! Datetime [y,m,d,h,m,s]
        ! Local variables
        integer :: pos
        ! Extract elements of the date string
        pos = index(format_str, 'yyyy')
        if (pos .gt. 0) then
            read(date_str(pos:pos+3),*) date_array(1)
        else
            date_array(1) = 0
        end if
        pos = index(format_str, 'mm')
        if (pos .gt. 0) then
            read(date_str(pos:pos+1),*) date_array(2)
        else
            date_array(2) = 0
        end if
        pos = index(format_str, 'dd')
        if (pos .gt. 0) then
            read(date_str(pos:pos+1),*) date_array(3)
        else
            date_array(3) = 0
        end if
        pos = index(format_str, 'HH')
        if (pos .gt. 0) then
            read(date_str(pos:pos+1),*) date_array(4)
        else
            date_array(4) = 0
        end if
        pos = index(format_str, 'MM')
        if (pos .gt. 0) then
            read(date_str(pos:pos+1),*) date_array(5)
        else
            date_array(5) = 0
        end if
        pos = index(format_str, 'SS')
        if (pos .gt. 0) then
            read(date_str(pos:pos+1),*) date_array(6)
        else
            date_array(6) = 0
        end if
    end subroutine datestr_to_date
Call graph
uemep_calculate_emissions_for_emep calls datestr_to_date, uemep_read_meteo_nc, uemep_read_monthly_and_daily_shipping_asi_data, uemep_read_roadlink_emission_data, uemep_read_weekly_shipping_asi_data
uemep_read_config calls datestr_to_date
uemep_read_meteo_nc calls datestr_to_date
uemep_read_monthly_and_daily_shipping_asi_data calls datestr_to_date
uemep_read_roadlink_emission_data calls datestr_to_date
uemep_read_weekly_shipping_asi_data calls datestr_to_date
uemep_v6 calls uemep_calculate_emissions_for_emep, uemep_read_config, uemep_read_meteo_nc, uemep_read_monthly_and_daily_shipping_asi_data, uemep_read_roadlink_emission_data, uemep_read_weekly_shipping_asi_data