lambert2lb2_uEMEP – uEMEP
lambert2lb2_uEMEP Subroutine
31 statements
Source File
public subroutine lambert2lb2_uEMEP(x, y, gl, gb, projection_attr)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: x
real, intent(in) :: y
real, intent(out) :: gl
real, intent(out) :: gb
double precision, intent(in) :: projection_attr(10)
Called by
Source Code
    subroutine lambert2lb2_uEMEP(x, y, gl, gb, projection_attr)
        double precision, intent(in) :: projection_attr(10)
        real, intent(in) :: x, y
        real, intent(out):: gl, gb
        real :: r, t
        real :: earth_radius, k, F, y0
        real :: deg2rad, rad2deg, k_lambert, lat0_lambert
        real :: lat0
        real :: lat_stand1_lambert, lat_stand2_lambert, lon0, lat0_in
        lat_stand1_lambert = projection_attr(1)
        lat_stand2_lambert = projection_attr(2)
        lon0 = projection_attr(3)
        lat0_in = projection_attr(4)
        earth_radius = projection_attr(5)
        deg2rad = PI/180.0
        rad2deg = 180.0/PI
        if (lat_stand1_lambert .eq. lat_stand2_lambert) then
            k_lambert = sin(PI/180.0*lat0_in)
        else
            k_lambert = log(cos(deg2rad*lat_stand1_lambert)/cos(deg2rad*lat_stand2_lambert))/ &
                (log(tan(0.25*PI + 0.5*deg2rad*lat_stand2_lambert)/tan(0.25*PI + 0.5*deg2rad*lat_stand1_lambert)))
        end if
        lat0_lambert = rad2deg*asin(k_lambert)
        lat0 = lat0_in
        k = k_lambert
        F = earth_radius*cos(PI/180.0*lat_stand1_lambert)*(tan(PI/4.0+PI/360.0*lat_stand1_lambert)**k)/k
        y0 = F*tan(PI/4.0 - PI/360.0*lat0)**k
        r = sqrt(x*x + (y0 - y)*(y0 - y))
        t = atan(x/(y0 - y))
        gb = 2*180.0/PI*atan((F/r)**(1.0/k)) - 90.0
        gl = lon0 + 180.0/PI*t/k
    end subroutine lambert2lb2_uEMEP
Call graph
proj2ll calls lambert2lb2_uemep
uemep_calculate_emissions_for_emep calls lambert2lb2_uemep, uemep_grid_roads, uemep_read_meteo_nc, uemep_read_monthly_and_daily_shipping_asi_data, uemep_read_roadlink_data_ascii, uemep_read_weekly_shipping_asi_data
read_country_bounding_box_data calls proj2ll
uemep_define_subgrid calls proj2ll
uemep_define_subgrid_extent calls proj2ll
uemep_grid_roads calls proj2ll
uemep_preaggregate_shipping_asi_data calls proj2ll
uemep_read_emep calls proj2ll
uemep_read_landuse_rivm_data calls proj2ll
uemep_read_meteo_nc calls proj2ll
uemep_read_monthly_and_daily_shipping_asi_data calls proj2ll
uemep_read_netcdf_landuse_latlon calls proj2ll
uemep_read_netcdf_population_latlon calls proj2ll
uemep_read_netcdf_shipping_latlon calls proj2ll
uemep_read_roadlink_data_ascii calls proj2ll
uemep_read_weekly_shipping_asi_data calls proj2ll
uemep_region_mask_new calls proj2ll
uemep_set_region_tile_grids calls proj2ll
uemep_set_tile_grids calls proj2ll
uemep_v6 calls uemep_calculate_emissions_for_emep, read_country_bounding_box_data, uemep_define_subgrid, uemep_define_subgrid_extent, uemep_grid_roads, uemep_preaggregate_shipping_asi_data, uemep_read_emep, uemep_read_landuse_rivm_data, uemep_read_meteo_nc, uemep_read_monthly_and_daily_shipping_asi_data, uemep_read_netcdf_landuse_latlon, uemep_read_netcdf_population_latlon, uemep_read_netcdf_shipping_latlon, uemep_read_roadlink_data_ascii, uemep_read_weekly_shipping_asi_data, uemep_region_mask_new, uemep_set_region_tile_grids, uemep_set_tile_grids