lb2lambert2_uEMEP – uEMEP
lb2lambert2_uEMEP Subroutine
30 statements
Source File
public subroutine lb2lambert2_uEMEP(x, y, gl, gb, projection_attr)
Arguments
Type Intent Optional Attributes Name
real, intent(out) :: x
real, intent(out) :: y
real, intent(in) :: gl
real, intent(in) :: gb
double precision, intent(in) :: projection_attr(10)
Called by
Source Code
    subroutine lb2lambert2_uEMEP(x, y, gl, gb, projection_attr)
        double precision, intent(in) :: projection_attr(10)
        real, intent(in) :: gl, gb
        real, intent(out):: x, y
        real :: r
        real :: earth_radius, k, F, y0
        real :: deg2rad, rad2deg, k_lambert, lat0_lambert
        real :: lat0
        real :: lat_stand1_lambert, lat_stand2_lambert, lon0, lat0_in
        lat_stand1_lambert = projection_attr(1)
        lat_stand2_lambert = projection_attr(2)
        lon0 = projection_attr(3)
        lat0_in = projection_attr(4)
        earth_radius = projection_attr(5)
        deg2rad = PI/180.0
        rad2deg = 180.0/PI
        if (lat_stand1_lambert .eq. lat_stand2_lambert) then
            k_lambert = sin(PI/180.0*lat0_in)
        else
            k_lambert = log(cos(deg2rad*lat_stand1_lambert)/cos(deg2rad*lat_stand2_lambert))/ &
                (log(tan(0.25*PI + 0.5*deg2rad*lat_stand2_lambert)/tan(0.25*PI + 0.5*deg2rad*lat_stand1_lambert)))
        end if
        lat0_lambert = rad2deg*asin(k_lambert)
        lat0 = lat0_in
        k = k_lambert
        F = earth_radius*cos(PI/180.0*lat_stand1_lambert)*(tan(PI/4.0 + PI/360.0*lat_stand1_lambert)**k)/k
        y0 = F*tan(PI/4.0 - PI/360.0*lat0)**k
        r = F*tan(PI/4.0 - PI/360.0*gb)**k
        x = r*sin(PI/180.0*k*(gl - lon0))
        y = y0 - r*cos(PI/180.0*k*(gl - lon0))
    end subroutine lb2lambert2_uEMEP
Call graph
ll2proj calls lb2lambert2_uemep
uemep_crossreference_grids calls lb2lambert2_uemep
uemep_define_subgrid calls lb2lambert2_uemep
uemep_grid_roads calls lb2lambert2_uemep
uemep_read_agriculture_rivm_data calls lb2lambert2_uemep
uemep_read_emep calls lb2lambert2_uemep
uemep_read_industry_data calls lb2lambert2_uemep
uemep_read_landuse_rivm_data calls lb2lambert2_uemep, uemep_crossreference_grids
uemep_read_meteo_nc calls lb2lambert2_uemep
uemep_read_monthly_and_daily_shipping_asi_data calls lb2lambert2_uemep
uemep_read_roadlink_data_ascii calls lb2lambert2_uemep
uemep_read_rwc_heating_data calls lb2lambert2_uemep
uemep_read_shipping_asi_data calls lb2lambert2_uemep
uemep_read_weekly_shipping_asi_data calls lb2lambert2_uemep
uemep_subgrid_emission_emep calls lb2lambert2_uemep
uemep_calculate_emissions_for_emep calls uemep_grid_roads, uemep_read_agriculture_rivm_data, uemep_read_industry_data, uemep_read_meteo_nc, uemep_read_monthly_and_daily_shipping_asi_data, uemep_read_roadlink_data_ascii, uemep_read_rwc_heating_data, uemep_read_shipping_asi_data, uemep_read_weekly_shipping_asi_data
uemep_region_mask_new calls ll2proj
uemep_subgrid_emep_from_in_region calls ll2proj
uemep_v6 calls uemep_crossreference_grids, uemep_define_subgrid, uemep_grid_roads, uemep_read_agriculture_rivm_data, uemep_read_emep, uemep_read_industry_data, uemep_read_landuse_rivm_data, uemep_read_meteo_nc, uemep_read_monthly_and_daily_shipping_asi_data, uemep_read_roadlink_data_ascii, uemep_read_rwc_heating_data, uemep_read_shipping_asi_data, uemep_read_weekly_shipping_asi_data, uemep_subgrid_emission_emep, uemep_calculate_emissions_for_emep, uemep_region_mask_new, uemep_subgrid_emep_from_in_region