nxtdat – uEMEP
nxtdat Subroutine
22 statements
Source File
public subroutine nxtdat(un, leof)
The subroutine prepares for reading the next uncommented line of data from file
Arguments
Type Intent Optional Attributes Name
integer, intent(inout) :: un
logical, intent(out) :: leof
Called by
Source Code
    subroutine nxtdat(un, leof)
        !! The subroutine prepares for reading the next uncommented line of data from file
        integer, intent(inout) :: un
        logical, intent(out) :: leof
        ! Local variables
        character(len=256) :: txtstr
        integer :: io
        ! If file unit is non-positive then just return
        if (un .le. 0) return
        leof = .false.
        ! Read lines from file
        do
            read(un,"(a)", iostat=io) txtstr
            if (io /= 0) then
                leof = .true.
                exit
            else
                if (txtstr(1:1) == "*" .or. txtstr(1:1) == "{" .or. txtstr(1:1) == "#") then
                    cycle
                else
                    backspace(un)
                    exit
                end if
            end if
        end do
    end subroutine nxtdat
Call graph
uemep_read_monthly_and_daily_shipping_asi_data calls nxtdat
uemep_read_roadlink_data_ascii calls nxtdat
uemep_read_roadlink_emission_data calls nxtdat
uemep_read_rwc_heating_data calls nxtdat
uemep_read_weekly_shipping_asi_data calls nxtdat
uemep_calculate_emissions_for_emep calls uemep_read_monthly_and_daily_shipping_asi_data, uemep_read_roadlink_data_ascii, uemep_read_roadlink_emission_data, uemep_read_rwc_heating_data, uemep_read_weekly_shipping_asi_data
uemep_v6 calls uemep_read_monthly_and_daily_shipping_asi_data, uemep_read_roadlink_data_ascii, uemep_read_roadlink_emission_data, uemep_read_rwc_heating_data, uemep_read_weekly_shipping_asi_data, uemep_calculate_emissions_for_emep