phih_func – uEMEP
phih_func Subroutine
16 statements
Source File
private subroutine phih_func(z, L, phih, phih_i)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: z
real, intent(in) :: L
real, intent(out) :: phih
real, intent(out) :: phih_i
Called by
Source Code
    subroutine phih_func(z,L,phih,phih_i)
        implicit none
        real, intent(in) :: z,L
        real, intent(out) :: phih,phih_i
        real a,b,q
        parameter (a=16.,b=5.,q=-0.5)
        real eps
        eps=z/L
        if (eps.ge.0) then
            phih=1.+b*eps
            phih_i=-b*eps
        else
            phih=exp(q*log((1.-a*eps)))
            phih_i=2.*log((1.+1./phih)/2.)
        endif
    end subroutine phih_func
Call graph
kz_func calls phih_func
uemep_set_dispersion_sigma_kz calls kz_func
uemep_subgrid_deposition calls uemep_set_dispersion_sigma_kz
uemep_subgrid_dispersion calls uemep_set_dispersion_sigma_kz, uemep_subgrid_dispersion_integral
uemep_subgrid_dispersion_integral calls uemep_set_dispersion_sigma_kz
uemep_v6 calls uemep_subgrid_deposition, uemep_subgrid_dispersion