PS2LL_spherical – uEMEP
PS2LL_spherical Subroutine
28 statements
Source File
private subroutine PS2LL_spherical(x, y, lon, lat, projection_attr)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: x
real, intent(in) :: y
real, intent(out) :: lon
real, intent(out) :: lat
double precision, intent(in) :: projection_attr(10)
Called by
Source Code
    subroutine PS2LL_spherical(x, y, lon, lat, projection_attr)
        ! https://mathworld.wolfram.com/StereographicProjection.html
        ! grid_mapping_name = Polar_Stereographic
        ! Map parameters:
        ! longitude_of_projection_origin
        ! latitude_of_projection_origin
        ! false_easting - This parameter is optional (default is 0)
        ! false_northing - This parameter is optional (default is 0)
        ! NOTE scale_factor_at_projection_origin =0.5(1+sin(Standard Parallel))
        double precision, intent(in) :: projection_attr(10)
        real, intent(out) :: lon, lat
        real, intent(in) :: x, y
        real :: r, rho, c
        real :: earth_radius
        real :: deg2rad, rad2deg
        real :: lat0, lat0_in, lon0, lon0_in
        real :: false_easting,false_northing
        real :: scaling
        lon0_in = projection_attr(1)
        lat0_in = projection_attr(2)
        false_easting = projection_attr(3)
        false_northing = projection_attr(4)
        earth_radius = projection_attr(5)
        scaling = projection_attr(6)
        deg2rad = PI/180.0
        rad2deg = 180.0/PI
        r = earth_radius
        lat0 = lat0_in*deg2rad
        lon0 = lon0_in*deg2rad
        rho = sqrt((x - false_easting)*(x - false_easting) + (y-false_northing)*(y - false_northing))
        c = 2.0*atan(rho*0.5/r/scaling)
        lat = asin(cos(c)*sin(lat0) + (y - false_northing)/rho*sin(c)*cos(lat0))
        lon = lon0 + atan((x - false_easting)*sin(c)/(rho*cos(lat0)*cos(c) - (y - false_northing)*sin(lat0)*sin(c)))
        lat = lat*rad2deg
        lon = lon*rad2deg
    end subroutine PS2LL_spherical
Call graph
proj2ll calls ps2ll_spherical
read_country_bounding_box_data calls proj2ll
uemep_define_subgrid calls proj2ll
uemep_define_subgrid_extent calls proj2ll
uemep_grid_roads calls proj2ll
uemep_preaggregate_shipping_asi_data calls proj2ll
uemep_read_emep calls proj2ll
uemep_read_landuse_rivm_data calls proj2ll
uemep_read_meteo_nc calls proj2ll
uemep_read_monthly_and_daily_shipping_asi_data calls proj2ll
uemep_read_netcdf_landuse_latlon calls proj2ll
uemep_read_netcdf_population_latlon calls proj2ll
uemep_read_netcdf_shipping_latlon calls proj2ll
uemep_read_roadlink_data_ascii calls proj2ll
uemep_read_weekly_shipping_asi_data calls proj2ll
uemep_region_mask_new calls proj2ll
uemep_set_region_tile_grids calls proj2ll
uemep_set_tile_grids calls proj2ll
uemep_calculate_emissions_for_emep calls uemep_grid_roads, uemep_read_meteo_nc, uemep_read_monthly_and_daily_shipping_asi_data, uemep_read_roadlink_data_ascii, uemep_read_weekly_shipping_asi_data
uemep calls read_country_bounding_box_data, uemep_define_subgrid, uemep_define_subgrid_extent, uemep_grid_roads, uemep_preaggregate_shipping_asi_data, uemep_read_emep, uemep_read_landuse_rivm_data, uemep_read_meteo_nc, uemep_read_monthly_and_daily_shipping_asi_data, uemep_read_netcdf_landuse_latlon, uemep_read_netcdf_population_latlon, uemep_read_netcdf_shipping_latlon, uemep_read_roadlink_data_ascii, uemep_read_weekly_shipping_asi_data, uemep_region_mask_new, uemep_set_region_tile_grids, uemep_set_tile_grids, uemep_calculate_emissions_for_emep