RDM2LL – uEMEP
RDM2LL Subroutine
17 statements
Source File
public subroutine RDM2LL(y, x, lat, lon)
Arguments
Type Intent Optional Attributes Name
real :: y
real :: x
real :: lat
real :: lon
Called by
Source Code
    subroutine RDM2LL(y,x,lat,lon)
        implicit none
        real x,y,lat,lon
        real referenceRdX,referenceRdY,referenceWgs84X,referenceWgs84Y
        real dX,dY
        real sumN,sumE
        !SOURCE:   https://www.roelvanlisdonk.nl/2012/11/21/simple-way-for-converting-rijksdriehoek-coordinates-to-lat-and-long-wgs84-in-c/
        !referentie coordinated RDM
        referenceRdX = 155000
        referenceRdY = 463000
        !The city "Amsterfoort" is used as reference "WGS84" coordinate.
        referenceWgs84X = 52.15517
        referenceWgs84Y = 5.387206
        dX = (x - referenceRdX) * 10**(-5.0)
        dY = (y - referenceRdY) * 10**(-5.0)
        sumN = (3235.65389 * dY) + (-32.58297 * (dX**2)) + (-0.2475 * (dY**2)) + (-0.84978 * (dX**2) * dY) + (-0.0655 * (dY**3)) + (-0.01709 * (dX**2) * (dY**2)) + (-0.00738 * dX) + (0.0053 * (dX**4)) + (-0.00039 * (dX**2) * (dY**3)) + (0.00033 * (dX**4) * dY) + (-0.00012 * dX * dY)
        sumE = (5260.52916 * dX) + (105.94684 * dX * dY) + (2.45656 * dX * (dY**2)) + (-0.81885 * (dX**3)) + (0.05594 * dX * (dY**3)) + (-0.05607 * (dX**3) * dY) + (0.01199 * dY) + (-0.00256 *(dX**3) * (dY**2)) + (0.00128 * dX * (dY**4)) + (0.00022 * (dY**2)) + (-0.00022 *(dX**2)) + (0.00026 * (dX**5))
        lat = referenceWgs84X + (sumN / 3600.)
        lon = referenceWgs84Y + (sumE / 3600.)
    end subroutine RDM2LL
Call graph
proj2ll calls rdm2ll
uemep_read_agriculture_rivm_data calls rdm2ll
read_country_bounding_box_data calls proj2ll
uemep_calculate_emissions_for_emep calls uemep_read_agriculture_rivm_data, uemep_grid_roads, uemep_read_meteo_nc, uemep_read_monthly_and_daily_shipping_asi_data, uemep_read_roadlink_data_ascii, uemep_read_weekly_shipping_asi_data
uemep_define_subgrid calls proj2ll
uemep_define_subgrid_extent calls proj2ll
uemep_grid_roads calls proj2ll
uemep_preaggregate_shipping_asi_data calls proj2ll
uemep_read_emep calls proj2ll
uemep_read_landuse_rivm_data calls proj2ll
uemep_read_meteo_nc calls proj2ll
uemep_read_monthly_and_daily_shipping_asi_data calls proj2ll
uemep_read_netcdf_landuse_latlon calls proj2ll
uemep_read_netcdf_population_latlon calls proj2ll
uemep_read_netcdf_shipping_latlon calls proj2ll
uemep_read_roadlink_data_ascii calls proj2ll
uemep_read_weekly_shipping_asi_data calls proj2ll
uemep_region_mask_new calls proj2ll
uemep_set_region_tile_grids calls proj2ll
uemep_set_tile_grids calls proj2ll
uemep_v6 calls uemep_read_agriculture_rivm_data, read_country_bounding_box_data, uemep_calculate_emissions_for_emep, uemep_define_subgrid, uemep_define_subgrid_extent, uemep_grid_roads, uemep_preaggregate_shipping_asi_data, uemep_read_emep, uemep_read_landuse_rivm_data, uemep_read_meteo_nc, uemep_read_monthly_and_daily_shipping_asi_data, uemep_read_netcdf_landuse_latlon, uemep_read_netcdf_population_latlon, uemep_read_netcdf_shipping_latlon, uemep_read_roadlink_data_ascii, uemep_read_weekly_shipping_asi_data, uemep_region_mask_new, uemep_set_region_tile_grids, uemep_set_tile_grids