sigma0_traffic_func – uEMEP
sigma0_traffic_func Function
12 statements
Source File
private function sigma0_traffic_func(speed)
Arguments
Type Intent Optional Attributes Name
real :: speed
Return Value real
Called by
Source Code
    function sigma0_traffic_func(speed)
        implicit none
        real:: speed
        real:: sigma0_traffic_func
        real :: min_sigma=0.5
        real :: max_sigma=3.
        real :: min_speed=40.
        real :: max_speed=100.
        real :: gradient
        gradient=(max_sigma-min_sigma)/(max_speed-min_speed)
        sigma0_traffic_func=min(max(min_sigma+(speed-min_speed)*gradient,min_sigma),max_sigma)
    end function sigma0_traffic_func
Call graph
uemep_grid_roads calls sigma0_traffic_func
uemep_calculate_emissions_for_emep calls uemep_grid_roads
uemep calls uemep_grid_roads, uemep_calculate_emissions_for_emep