u_profile_neutral_val_func – uEMEP
u_profile_neutral_val_func Subroutine
12 statements
Source File
public subroutine u_profile_neutral_val_func(z, u_val, z_val_in, z_pbl, z0, u, u_star0)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: z
real, intent(in) :: u_val
real, intent(in) :: z_val_in
real, intent(in) :: z_pbl
real, intent(in) :: z0
real, intent(out) :: u
real, intent(out) :: u_star0
Called by
Source Code
    subroutine u_profile_neutral_val_func(z,u_val,z_val_in,z_pbl,z0,u,u_star0)
        implicit none
        real, intent(in) :: z,u_val,z_val_in,z_pbl,z0
        real, intent(out) :: u,u_star0
        real kappa
        parameter (kappa=0.4)
        real z_l,z_val
        !If the input height is above the boundary layer then set the height to pbl height and calculate
        z_val=min(z_val_in,z_pbl)
        z_l=0.4*z_pbl
        u_star0=u_val*kappa/(log(z_val/z0)+kappa*z_val/z_l*(1-z_val/2./z_pbl)-z_val/z_pbl)
        u=u_star0/kappa*(log(z/z0)+kappa*z/z_l*(1-z/2./z_pbl)-z/z_pbl)
    end subroutine u_profile_neutral_val_func
Call graph
uemep_create_wind_field calls u_profile_neutral_val_func
uemep_set_dispersion_sigma_kz calls u_profile_neutral_val_func
uemep_subgrid_deposition calls u_profile_neutral_val_func, uemep_create_wind_field, uemep_set_dispersion_sigma_kz
uemep_subgrid_dispersion calls u_profile_neutral_val_func, uemep_set_dispersion_sigma_kz, uemep_subgrid_dispersion_integral
uemep_subgrid_dispersion_integral calls u_profile_neutral_val_func, uemep_set_dispersion_sigma_kz
uemep_v6 calls uemep_subgrid_deposition, uemep_subgrid_dispersion