uEMEP_set_dispersion_sigma_simple – uEMEP
uEMEP_set_dispersion_sigma_simple Subroutine
22 statements
Source File
public subroutine uEMEP_set_dispersion_sigma_simple(sig_z_00, sig_y_00, sigy_0_subgid_width_scale, subgrid_delta, delta_wind, x, sig_z, sig_y, sig_z_0, sig_y_0)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: sig_z_00
real, intent(in) :: sig_y_00
real, intent(in) :: sigy_0_subgid_width_scale
real, intent(in) :: subgrid_delta(2)
real, intent(in) :: delta_wind
real, intent(in) :: x
real, intent(out) :: sig_z
real, intent(out) :: sig_y
real, intent(out) :: sig_z_0
real, intent(out) :: sig_y_0
Called by
Source Code
    subroutine uEMEP_set_dispersion_sigma_simple(sig_z_00,sig_y_00,sigy_0_subgid_width_scale,subgrid_delta,delta_wind,x,sig_z,sig_y,sig_z_0,sig_y_0)
        implicit none
        real, intent(in) :: sig_z_00,sig_y_00,sigy_0_subgid_width_scale,subgrid_delta(2),delta_wind,x
        real, intent(out) :: sig_z,sig_y,sig_z_0,sig_y_0
        real ay,by,az,bz
        real min_xy
        !Set the psedo dispersion parameters for neutral conditions
        !From Klug
        !ay=0.32
        !by=0.78
        !az=0.22
        !bz=0.78
        !From Liu
        !ay=0.64
        !by=0.46!From Liu
        !az=0.088!From Liu
        !bz=0.72!From Liu 0.72
        !Alternative ASME
        !ay=0.14
        !by=0.9
        !az=0.22
        !bz=0.85
        !Update from K_z fitting
        ay=0.32
        by=0.78
        !az=0.19
        !bz=0.77
        az=0.125
        bz=0.85 !For z0=0.1, corresponding to the same as K_z for wind height at emission source of 1 m
        az=0.245
        bz=0.711 !For z0=0.3, corresponding to the same as K_z for wind height at average of emission source of 1 m and zc
        az=0.21
        bz=0.79 !For z0=0.3, corresponding to the same as K_z for wind height at emission source of 1 m
        !Consistant with uEMEP_set_dispersion_params_PG needs to be fixed. Just one call to the parameters, one calle to the sigma calculation
        az=0.2
        bz=0.75
        min_xy=(subgrid_delta(1)+subgrid_delta(2))/4.
        !Set sig_y_0 to be half of the average x,y grid size
        !Add this here ay*exp(by*log(min_xy)) to be the same as sig_z and the same as the  Kz calculation
        !Does not mean it is correct, just closer to the Kz which is perhaps not so correct
        sig_y_0=sig_y_00+min_xy*sigy_0_subgid_width_scale+ay*exp(by*log(min_xy))
        !Set sig_z_0 to be the size of the plume after travelling half of the grid size
        sig_z_0=sig_z_00+az*exp(bz*log(min_xy))
        !Set sig_y and sig_z = sig_0 + a*x^b +x*delata_wind
        sig_y=sig_y_0+ay*exp(by*log(x))+x*abs(delta_wind)
        sig_z=sig_z_0+az*exp(bz*log(x))
    end subroutine uEMEP_set_dispersion_sigma_simple
Call graph
uemep_create_wind_field calls uemep_set_dispersion_sigma_simple
uemep_subgrid_deposition calls uemep_set_dispersion_sigma_simple, uemep_create_wind_field
uemep_subgrid_dispersion calls uemep_set_dispersion_sigma_simple, uemep_subgrid_dispersion_integral
uemep_subgrid_dispersion_integral calls uemep_set_dispersion_sigma_simple
uemep_v6 calls uemep_subgrid_deposition, uemep_subgrid_dispersion