uEMEP_set_dispersion_params_simple – uEMEP
uEMEP_set_dispersion_params_simple Subroutine
11 statements
Source File
public subroutine uEMEP_set_dispersion_params_simple(source_index, subsource_index)
Uses
uEMEP_definitions
Arguments
Type Intent Optional Attributes Name
integer :: source_index
integer :: subsource_index
Called by
Source Code
    subroutine uEMEP_set_dispersion_params_simple(source_index,subsource_index)
        use uEMEP_definitions
        implicit none
        integer source_index,subsource_index
        !Set the psedo dispersion parameters here.
        ay(source_index,subsource_index)=0.32
        by(source_index,subsource_index)=0.78
        az(source_index,subsource_index)=0.22
        bz(source_index,subsource_index)=0.78
        !ay(source_index,subsource_index)=0.64!From Liu
        !by(source_index,subsource_index)=0.46!From Liu
        !az(source_index,subsource_index)=0.088!From Liu
        !bz(source_index,subsource_index)=0.72!From Liu 0.72
        !ay(source_index,subsource_index)=0.32
        !by(source_index,subsource_index)=0.78
        az(source_index,subsource_index)=0.2
        bz(source_index,subsource_index)=0.75
        !Alternative to ASME
        !ay(source_index,subsource_index)=0.14
        !by(source_index,subsource_index)=0.9
        !az(source_index,subsource_index)=0.22
        !bz(source_index,subsource_index)=0.85
        !sig_y_0(source_index,subsource_index)=sig_y_00(source_index,subsource_index)
        !sig_z_0(source_index,subsource_index)=sig_z_00(source_index,subsource_index)
        !sig_y_0(source_index,subsource_index)=sig_y_00(source_index,subsource_index)+sqrt(emission_subgrid_delta(x_dim_index,source_index)*emission_subgrid_delta(y_dim_index,source_index))/2.
        !sig_z_0(source_index,subsource_index)=sig_z_00(source_index,subsource_index)+az(source_index,subsource_index)*exp(bz(source_index,subsource_index)*log(sig_y_0(source_index,subsource_index)))
        !h_emis(source_index,subsource_index)=1.
        !z_rec(source_index,subsource_index)=2.
        !Exceptions
        !ay=ay*3.
        !az=az*5.
        !bz=0.95
    end subroutine uEMEP_set_dispersion_params_simple
Call graph
uemep_subgrid_deposition calls uemep_set_dispersion_params_simple
uemep_subgrid_dispersion calls uemep_set_dispersion_params_simple, uemep_subgrid_dispersion_integral
uemep_subgrid_dispersion_integral calls uemep_set_dispersion_params_simple
uemep_v6 calls uemep_subgrid_deposition, uemep_subgrid_dispersion