read_name – uEMEP
read_name Interface
7 statements
Source File
private interface read_name
Calls
Module Procedures
public function read_name_real(name_str, default_val, unit_in, unit_out) result(res)
Reads single precision value from name file
Read more…
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: name_str
Name of value in name file
real, intent(in) :: default_val
Default value
integer, intent(in) :: unit_in
Name file unit
integer, intent(in) :: unit_out
Log file unit
Return Value real
Value found in name file (or default value)
public function read_name_double(name_str, default_val, unit_in, unit_out) result(res)
Reads double precision value from name file
Read more…
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: name_str
Name of value in name file
real(kind=dp), intent(in) :: default_val
Default value
integer, intent(in) :: unit_in
Name file unit
integer, intent(in) :: unit_out
Log file unit
Return Value real(kind=dp)
Value found in name file (or default value)
public function read_name_integer(name_str, default_val, unit_in, unit_out) result(res)
Reads integer value from name file
Read more…
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: name_str
Name of value in name file
integer, intent(in) :: default_val
Default value
integer, intent(in) :: unit_in
Name file unit
integer, intent(in) :: unit_out
Log file unit
Return Value integer
Value found in name file (or default value)
public function read_name_char(name_str, default_val, unit_in, unit_out) result(res)
Reads string from name file
Read more…
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: name_str
Name of string in name file
character(len=*), intent(in) :: default_val
Default string
integer, intent(in) :: unit_in
Name file unit
integer, intent(in) :: unit_out
Log file unit
Return Value character(len=:), allocatable
String found in name file (or default string)
public function read_name_logical(name_str, default_val, unit_in, unit_out) result(res)
Reads boolean value from name file
Read more…
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: name_str
Name of value in name file
logical, intent(in) :: default_val
Default value
integer, intent(in) :: unit_in
Name file unit
integer, intent(in) :: unit_out
Log file unit
Return Value logical
Call graph
read_name calls read_name_char, read_name_double, read_name_integer, read_name_logical, read_name_real